### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DiabolicAngeL** [freeman507/phasmophobia_assistant#1]
Are we allowed to upload the app on google play?

Thanks!

**Comment by freeman507** [comment]
Hi, DiabolicAngel, it's already in Play Store. https://play.google.com/store/apps/details?id=br.com.pacientevirtual.phasmophobiaassistant

**Comment by DiabolicAngeL** [comment]
Hello, yes I've seen it, I'm just asking to know if we are allowed to customize it, change it to fit our "brand" and re-upload it

**Comment by freeman507** [comment]
The answer is yes, but keep in mind that you have to keep the:
Terms of privacy of users;
Keep the name;
Don't monetize it in any way;
Put the reference of the project and the start project;

**Comment by DiabolicAngeL** [comment]
Ok, thank you very much!
